from .multi_dialog.multi_dialog import create_multi_dialog_tab_page
from .single_audio.single_audio import create_single_audio_tab_page
from .subtitle_only.subtitle_only import create_subtitle_only_tab_page
